# Go-RocketMQ 集群配置示例
# 本配置文件展示了如何配置一个完整的RocketMQ集群

# NameServer配置
nameserver:
  # 监听地址
  listen_addr: "0.0.0.0:9876"
  # 日志级别
  log_level: "INFO"
  # 日志文件路径
  log_file: "/var/log/rocketmq/nameserver.log"
  # 路由信息清理间隔（秒）
  route_info_clean_interval: 10
  # Broker心跳超时时间（秒）
  broker_heartbeat_timeout: 120

# Broker集群配置
brokers:
  # Broker-A 主节点
  - name: "broker-a"
    role: "master"
    broker_id: 0
    listen_port: 10911
    ha_listen_port: 10912
    nameserver_addr: "127.0.0.1:9876"
    cluster_name: "DefaultCluster"
    
    # 存储配置
    store:
      # 存储根目录
      store_path_root: "/data/rocketmq/broker-a"
      # CommitLog存储路径
      store_path_commitlog: "/data/rocketmq/broker-a/commitlog"
      # ConsumeQueue存储路径
      store_path_consume_queue: "/data/rocketmq/broker-a/consumequeue"
      # 索引文件存储路径
      store_path_index: "/data/rocketmq/broker-a/index"
      # CommitLog文件大小（字节）
      mapped_file_size_commitlog: 1073741824  # 1GB
      # ConsumeQueue文件大小（字节）
      mapped_file_size_consume_queue: 6000000  # ~6MB
      # 刷盘方式：SYNC_FLUSH（同步）或 ASYNC_FLUSH（异步）
      flush_disk_type: "ASYNC_FLUSH"
      # 刷盘间隔（毫秒）
      flush_interval_commitlog: 500
      flush_interval_consume_queue: 1000
    
    # 高可用配置
    ha:
      # 主从同步方式：SYNC（同步）或 ASYNC（异步）
      broker_role: "SYNC_MASTER"
      # 从节点同步超时时间（毫秒）
      ha_send_heartbeat_interval: 5000
      # 主节点等待从节点确认超时时间（毫秒）
      ha_housekeeping_interval: 20000
    
    # 性能配置
    performance:
      # 发送消息线程池大小
      send_message_thread_pool_nums: 16
      # 拉取消息线程池大小
      pull_message_thread_pool_nums: 16
      # 查询消息线程池大小
      query_message_thread_pool_nums: 8
      # 管理Broker线程池大小
      admin_broker_thread_pool_nums: 16
      # 客户端管理线程池大小
      client_manage_thread_pool_nums: 32
      # 消费者管理线程池大小
      consumer_manage_thread_pool_nums: 32
    
    # 日志配置
    logging:
      log_level: "INFO"
      log_file: "/var/log/rocketmq/broker-a.log"
      log_max_size: "100MB"
      log_max_files: 10

  # Broker-A 从节点
  - name: "broker-a-slave"
    role: "slave"
    broker_id: 1
    listen_port: 10921
    ha_listen_port: 10922
    nameserver_addr: "127.0.0.1:9876"
    cluster_name: "DefaultCluster"
    
    # 存储配置
    store:
      store_path_root: "/data/rocketmq/broker-a-slave"
      store_path_commitlog: "/data/rocketmq/broker-a-slave/commitlog"
      store_path_consume_queue: "/data/rocketmq/broker-a-slave/consumequeue"
      store_path_index: "/data/rocketmq/broker-a-slave/index"
      mapped_file_size_commitlog: 1073741824
      mapped_file_size_consume_queue: 6000000
      flush_disk_type: "ASYNC_FLUSH"
      flush_interval_commitlog: 500
      flush_interval_consume_queue: 1000
    
    # 高可用配置
    ha:
      broker_role: "SLAVE"
      # 从主节点同步数据的地址
      ha_master_address: "127.0.0.1:10912"
      ha_send_heartbeat_interval: 5000
      ha_housekeeping_interval: 20000
    
    # 性能配置
    performance:
      send_message_thread_pool_nums: 16
      pull_message_thread_pool_nums: 16
      query_message_thread_pool_nums: 8
      admin_broker_thread_pool_nums: 16
      client_manage_thread_pool_nums: 32
      consumer_manage_thread_pool_nums: 32
    
    # 日志配置
    logging:
      log_level: "INFO"
      log_file: "/var/log/rocketmq/broker-a-slave.log"
      log_max_size: "100MB"
      log_max_files: 10

  # Broker-B 主节点
  - name: "broker-b"
    role: "master"
    broker_id: 0
    listen_port: 10931
    ha_listen_port: 10932
    nameserver_addr: "127.0.0.1:9876"
    cluster_name: "DefaultCluster"
    
    # 存储配置
    store:
      store_path_root: "/data/rocketmq/broker-b"
      store_path_commitlog: "/data/rocketmq/broker-b/commitlog"
      store_path_consume_queue: "/data/rocketmq/broker-b/consumequeue"
      store_path_index: "/data/rocketmq/broker-b/index"
      mapped_file_size_commitlog: 1073741824
      mapped_file_size_consume_queue: 6000000
      flush_disk_type: "ASYNC_FLUSH"
      flush_interval_commitlog: 500
      flush_interval_consume_queue: 1000
    
    # 高可用配置
    ha:
      broker_role: "SYNC_MASTER"
      ha_send_heartbeat_interval: 5000
      ha_housekeeping_interval: 20000
    
    # 性能配置
    performance:
      send_message_thread_pool_nums: 16
      pull_message_thread_pool_nums: 16
      query_message_thread_pool_nums: 8
      admin_broker_thread_pool_nums: 16
      client_manage_thread_pool_nums: 32
      consumer_manage_thread_pool_nums: 32
    
    # 日志配置
    logging:
      log_level: "INFO"
      log_file: "/var/log/rocketmq/broker-b.log"
      log_max_size: "100MB"
      log_max_files: 10

  # Broker-B 从节点
  - name: "broker-b-slave"
    role: "slave"
    broker_id: 1
    listen_port: 10941
    ha_listen_port: 10942
    nameserver_addr: "127.0.0.1:9876"
    cluster_name: "DefaultCluster"
    
    # 存储配置
    store:
      store_path_root: "/data/rocketmq/broker-b-slave"
      store_path_commitlog: "/data/rocketmq/broker-b-slave/commitlog"
      store_path_consume_queue: "/data/rocketmq/broker-b-slave/consumequeue"
      store_path_index: "/data/rocketmq/broker-b-slave/index"
      mapped_file_size_commitlog: 1073741824
      mapped_file_size_consume_queue: 6000000
      flush_disk_type: "ASYNC_FLUSH"
      flush_interval_commitlog: 500
      flush_interval_consume_queue: 1000
    
    # 高可用配置
    ha:
      broker_role: "SLAVE"
      ha_master_address: "127.0.0.1:10932"
      ha_send_heartbeat_interval: 5000
      ha_housekeeping_interval: 20000
    
    # 性能配置
    performance:
      send_message_thread_pool_nums: 16
      pull_message_thread_pool_nums: 16
      query_message_thread_pool_nums: 8
      admin_broker_thread_pool_nums: 16
      client_manage_thread_pool_nums: 32
      consumer_manage_thread_pool_nums: 32
    
    # 日志配置
    logging:
      log_level: "INFO"
      log_file: "/var/log/rocketmq/broker-b-slave.log"
      log_max_size: "100MB"
      log_max_files: 10

# 客户端配置
client:
  # 生产者配置
  producer:
    # 默认生产者组
    default_producer_group: "DefaultProducerGroup"
    # 发送消息超时时间（毫秒）
    send_msg_timeout: 3000
    # 压缩消息体阈值（字节）
    compress_msg_body_over_howmuch: 4096
    # 重试次数
    retry_times_when_send_failed: 2
    # 异步发送失败重试次数
    retry_times_when_send_async_failed: 2
    # 是否在其他Broker重试
    retry_another_broker_when_not_store_ok: false
    # 最大消息大小（字节）
    max_message_size: 4194304  # 4MB
  
  # 消费者配置
  consumer:
    # 默认消费者组
    default_consumer_group: "DefaultConsumerGroup"
    # 消费模式：CLUSTERING（集群）或 BROADCASTING（广播）
    message_model: "CLUSTERING"
    # 消费起始位置：CONSUME_FROM_LAST_OFFSET 或 CONSUME_FROM_FIRST_OFFSET
    consume_from_where: "CONSUME_FROM_LAST_OFFSET"
    # 拉取消息间隔（毫秒）
    pull_interval: 1000
    # 拉取消息批次大小
    pull_batch_size: 32
    # 消费消息批次大小
    consume_message_batch_max_size: 1
    # 消费超时时间（分钟）
    consume_timeout: 15
    # 最大重试次数
    max_reconsume_times: 16
    # 消费线程数
    consume_thread_min: 20
    consume_thread_max: 64
    # 消费队列阈值
    consume_concurrently_max_span: 2000

# 监控配置
monitoring:
  # 是否启用监控
  enabled: true
  # 监控端口
  port: 8080
  # 监控路径
  path: "/metrics"
  # 统计间隔（秒）
  stats_interval: 60
  # 历史数据保留时间（小时）
  history_retention: 24

# 安全配置
security:
  # 是否启用ACL
  acl_enabled: false
  # ACL配置文件路径
  acl_config_file: "/etc/rocketmq/acl.yml"
  # 是否启用TLS
  tls_enabled: false
  # TLS证书文件路径
  tls_cert_file: "/etc/rocketmq/server.crt"
  # TLS私钥文件路径
  tls_key_file: "/etc/rocketmq/server.key"

# 全局配置
global:
  # 集群名称
  cluster_name: "DefaultCluster"
  # 是否启用自动创建Topic
  auto_create_topic_enable: true
  # 是否启用自动创建订阅组
  auto_create_subscription_group_enable: true
  # 默认Topic队列数
  default_topic_queue_nums: 4
  # 消息追踪
  message_trace_enable: true
  # 消息轨迹Topic
  message_trace_topic: "RMQ_SYS_TRACE_TOPIC"